export const INIT = '@@framework/INIT'
export const DECREMENT = 'DECREMENT'
export const INCREMENT = 'INCREMENT'
export const RESET = 'RESET'
export const EDIT_SUBTITLE = 'EDIT_SUBTITLE'
export const EDIT_TITLE = 'EDIT_TITLE'
