export const INIT = '@@framework/INIT'
export const OBSERVE_EVENT_STREAMS = '@@framework/OBSERVE_EVENT_STREAMS'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'
export const EDIT_SUBTITLE = 'EDIT_SUBTITLE'
export const UPDATE_RGB = 'UPDATE_RGB'
